# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider_principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='documento',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
    ]
